// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC70Rgza4otlap_b-l9ifQ4j9GVEQsqxZI',
    appId: '1:896476468358:web:86c7064186d95f224aad07',
    messagingSenderId: '896476468358',
    projectId: 'hotel-booking-service-85c78',
    authDomain: 'hotel-booking-service-85c78.firebaseapp.com',
    storageBucket: 'hotel-booking-service-85c78.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBELkviYIGkPro-C776PvArq9LGdeirGo4',
    appId: '1:896476468358:android:6b5bb6505ff3bd6d4aad07',
    messagingSenderId: '896476468358',
    projectId: 'hotel-booking-service-85c78',
    storageBucket: 'hotel-booking-service-85c78.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9Yb1-f9wMEx5wXW9I9kYNiKZAUtn3upM',
    appId: '1:896476468358:ios:0a81acb52f37a9f94aad07',
    messagingSenderId: '896476468358',
    projectId: 'hotel-booking-service-85c78',
    storageBucket: 'hotel-booking-service-85c78.firebasestorage.app',
    iosBundleId: 'com.example.hotelBookingServiceNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9Yb1-f9wMEx5wXW9I9kYNiKZAUtn3upM',
    appId: '1:896476468358:ios:0a81acb52f37a9f94aad07',
    messagingSenderId: '896476468358',
    projectId: 'hotel-booking-service-85c78',
    storageBucket: 'hotel-booking-service-85c78.firebasestorage.app',
    iosBundleId: 'com.example.hotelBookingServiceNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC70Rgza4otlap_b-l9ifQ4j9GVEQsqxZI',
    appId: '1:896476468358:web:f38d8fab23f09d5f4aad07',
    messagingSenderId: '896476468358',
    projectId: 'hotel-booking-service-85c78',
    authDomain: 'hotel-booking-service-85c78.firebaseapp.com',
    storageBucket: 'hotel-booking-service-85c78.firebasestorage.app',
  );
}
